project:
  type: website
resources:
    - "img/**"   # <-- The /** tells Quarto to only copy the files inside 'img', ignoring the rest of your site
exclude:
    - "posts/**/*.qmd"
    - "index.qmd"
    - "blog.qmd"
    - "book_list.qmd"
execute:
  freeze: auto

website:
  description: "A blog built with Quarto"
  site-url: https://bengin.netlify.app # you must change this appropriately for RSS feeds to work properly
  title: "Home"
  navbar:
    right:
      - icon: github
        href: https://github.com//quickbendelat
    left:
      - href: blog.qmd
        text: "Posts"
      - href: book_list.qmd
        text: "Book List"
format:
  html:
    theme:
      dark: darkly
      light: cosmo
    include-after-body: traffic.html
    css: styles.css



